### ISSUE TITLE
Add automation for AWS -> downstream consumers

### ISSUE THREAD

**Issue by jkodroff** [pulumi/github-issue-automation#30]
Create automation to create issues in downstream consumers of pulumi-aws whenever a release occurs:

1. pulumi-awsx
2. pulumi-eks
3. pulumi-aws-apigateway

Avoid the use of Zapier if possible because it requires manual config outside of IaC.

**Comment by stack72** [comment]
this work needs to be scalable for any component - e.g. kubernetes-ingress-nginx etc
